### ISSUE TITLE
camera no showing it is giving me blank

### ISSUE THREAD

**Issue by odejinmi** [waterbustech/waterbus-flutter-sdk#15]
E/CameraCaptureSession(24322): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): cancelRequest:641: Camera 1: Error clearing streaming request: Function not implemented (-38)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1414)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:99)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1341)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl$2.onDisconnected(CameraCaptureSessionImpl.java:790)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.CameraDeviceImpl$7.run(CameraDeviceImpl.java:267)
E/CameraCaptureSession(24322): 	at android.os.Handler.handleCallback(Handler.java:942)
E/CameraCaptureSession(24322): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(24322): 	at android.os.Looper.loopOnce(Looper.java:201)
E/CameraCaptureSession(24322): 	at android.os.Looper.loop(Looper.java:288)
E/CameraCaptureSession(24322): 	at android.os.HandlerThread.run(HandlerThread.java:67)
E/CameraCaptureSession(24322): Caused by: android.os.ServiceSpecificException: cancelRequest:641: Camera 1: Error clearing streaming request: Function not implemented (-38) (code 10)
E/CameraCaptureSession(24322): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3035)
E/CameraCaptureSession(24322): 	at android.os.Parcel.createException(Parcel.java:3005)
E/CameraCaptureSession(24322): 	at android.os.Parcel.readException(Parcel.java:2988)
E/CameraCaptureSession(24322): 	at android.os.Parcel.readException(Parcel.java:2930)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.cancelRequest(ICameraDeviceUser.java:648)
E/CameraCaptureSession(24322): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.cancelRequest(ICameraDeviceUserWrapper.java:97)
E/CameraCaptureSession(24322): 	... 9 more
I/org.webrtc.Logging(24322): Camera2Session: Stop internal
I/org.webrtc.Logging(24322): SurfaceTextureHelper: stopListening()
I/org.webrtc.Logging(24322): Camera2Session: Stop done
D/FlutterWebRTCPlugin(24322): CameraEventsHandler.onCameraDisconnected
I/org.webrtc.Logging(24322): CameraCapturer: Stop capture
I/org.webrtc.Logging(24322): CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging(24322): CameraCapturer: Stop capture done
I/org.webrtc.Logging(24322): Camera2Session: Camera device closed.
D/FlutterWebRTCPlugin(24322): CameraEventsHandler.onFirstFrameAvailable
I/org.webrtc.Logging(24322): Camera2Session: Stop camera2 session on camera 1
I/org.webrtc.Logging(24322): Camera2Session: Camera opened.
D/FlutterWebRTCPlugin(24322): onIceCandidate
D/FlutterWebRTCPlugin(24322): onIceCandidate
I/org.webrtc.Logging(24322): Camera2Session: Camera capture session configured.
I/org.webrtc.Logging(24322): Camera2Session: Stabilization not available.
I/org.webrtc.Logging(24322): Camera2Session: Auto-focus is not available.
I/org.webrtc.Logging(24322): Camera2Session: Camera device successfully started.
I/org.webrtc.Logging(24322): CameraCapturer: Create session done. Switch state: IDLE
I/org.webrtc.Logging(24322): SurfaceTextureHelper: Setting listener to org.webrtc.Camera2Session$CaptureSessionCallback$$ExternalSyntheticLambda0@6bebed

**Comment by lambiengcode** [comment]
let's follow this guide to config for Android: https://github.com/waterbustech/flutter-webrtc-plus?tab=readme-ov-file#android. I think lack of config for beauty filters.

**Comment by odejinmi** [comment]
thanks for the reply but new issue surface again:

e: file:///Users/user/StudioProjects/konnect/android/app/src/main/kotlin/com/example/konnect/FlutterViewEngine.kt:9:8 Unresolved reference: cl
e: file:///Users/user/StudioProjects/konnect/android/app/src/main/kotlin/com/example/konnect/FlutterViewEngine.kt:43:34 Unresolved reference: PipCallbackHelper
e: file:///Users/user/StudioProjects/konnect/android/app/src/main/kotlin/com/example/konnect/MainActivity.kt:13:12 Unresolved reference: waterbus
e: file:///Users/user/StudioProjects/konnect/android/app/src/main/kotlin/com/example/konnect/MainActivity.kt:18:35 Unresolved reference: ActivityMainBinding
e: file:///Users/user/StudioProjects/konnect/android/app/src/main/kotlin/com/example/konnect/MainActivity.kt:24:19 Unresolved reference: ActivityMainBinding

and this was added to my gradle

    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.23"
    implementation platform('com.google.firebase:firebase-bom:33.4.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-messaging-directboot:24.0.2'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.8.6"
//    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
    implementation "androidx.multidex:multidex:2.0.1"
    implementation 'tech.waterbus:gpupixel:1.0.2'

**Comment by odejinmi** [comment]
import cl.puntito.simple_pip_mode.PipCallbackHelper

this is the one package it was unable to install

**Comment by lurongshuang** [comment]
> 导入 cl.puntito.simple_pip_mode.PipCallbackHelper 导入 com.waterbus.wanted.databinding.ActivityMainBinding
> 
> 这是无法安装的两个包

Has the problem been resolved

**Comment by odejinmi** [comment]
please i need your help

**Comment by rn-netizen** [comment]
for me, it's more these opengl errors that cause the problems: 

GL ERROR 0x0505 GL_OUT_OF_MEMORY in func:active(), in file:../../../../../../../core/framebuffer.cc, at line 66
GL ERROR 0x0500 GL_INVALID_ENUM in func:readPixelsWithPBO(), in file:../../../../../../../target/target_raw_data_output.cc, at line 318
GL ERROR 0x0502 GL_INVALID_OPERATION in func:readPixelsWithPBO(), in file:../../../../../../../target/target_raw_data_output.cc, at line 319
GL ERROR 0x0500 GL_INVALID_ENUM in func:readPixelsWithPBO(), in file:../../../../../../../target/target_raw_data_output.cc, at line 321
GL ERROR 0x0500 GL_INVALID_ENUM in func:inactive(), in file:../../../../../../../core/framebuffer.cc, at line 71

**Comment by rn-netizen** [comment]
any ideas @lambiengcode ?

**Comment by lambiengcode** [comment]
@rn-netizen I'm migrating to v3 and it comes with the latest gpupixel, so it's not required config more for android! Let's use:

```yaml
flutter_webrtc_plus: ^0.14.1+3
```
